DEMOWEB/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    
    path("ckeditor/", include("ckeditor_uploader.urls")),
]

if settings.DEBUG: 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from os import name
from django.urls import path, include
from core.views import (
    ajax_add_review, 
    tag_list, 
    category_list_view, 
    category_product_list_view, 
    index, 
    product_detail_view, 
    product_list_view, 
    vendor_detail_view, 
    vendor_list_view, 
    search_view,
    filter_product,
    add_to_cart,
    cart_view,
    delete_item_from_cart,
    update_cart,
    checkout_view,
    payment_completed_view,
    payment_failed_view,
    customer_dashboard,
    order_detail,
    make_address_default,
    wishlistPage,
    add_to_wishlist,
    removeWishlist,
    contact,
    about_us,
    
    )
app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    #product
    path("products/", product_list_view, name="product-list"),
    path("product/<pid>", product_detail_view, name="product-detail"),

    #category
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),
    #vendor
    path("vendor/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>", vendor_detail_view, name="vendor-detail"),
    
    #Tags
    path("products/tag/<slug:tag_slug>", tag_list, name="tags"),

    #review
    path("ajax-add-review/<int:pid>/", ajax_add_review , name="ajax-add-review"),
    # Search
    path("search/", search_view, name="search"),
    #
    path("filter-products/", filter_product, name="filter-product"),
    #Add to cart
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    
    #Cart page
    path("cart/", cart_view, name="cart"),
    
    #delete product from cart
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    #update product from cart
    path("update-cart/", update_cart, name="update-cart"),
    
    #check out
    path("checkout/", checkout_view, name="checkout"),
    
    #paypal
    path('paypal/', include('paypal.standard.ipn.urls')),

    #paypal completed
    path('payment-completed/',payment_completed_view, name="payment-completed"),
    
    #paypal faile
    path('payment-failed/', payment_failed_view, name="payment-failed"),
    
    #dashboard
    path('dashboard/', customer_dashboard, name="dashboard"),
    
    #order detail
    path('dashboard/order/<int:id>', order_detail, name="order-detail"),
    
    #Make address default
    path('make-default-address/', make_address_default, name="make-default-address"),
    
    path('wishlist/', wishlistPage, name='wishlist'),
    
    #adding to wishlist
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),
    
    path('remove-wishlist/', removeWishlist, name='remove-wishlist'),
    
    path('contact/', contact, name='contact'),
    path('about-us/', about_us, name='about-us'),
    
     
]

core/forms.py
from django import forms 
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "write review"}))
    
    class Meta: 
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from core.admin import ProductAdmin
from core.models import Product, Category, Vendor, CartOrder, CartOrderItems, ProductImages, ProductReview, Wishlist, Address
from django.db.models import Count ,Avg
from taggit.models import Tag
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages
from userauths.models import Profile

from django.urls import reverse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.core import serializers


def index(request):
    # products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status = "published", featured=True)
    
    context = {
        "products":products
    }
    return render(request, 'core/index.html', context)

def product_list_view(request):
    products = Product.objects.filter(product_status = "published")
    
    context = {
        "products":products
    }
    return render(request, 'core/product-list.html', context)


def category_list_view(request):
    categories = Category.objects.all()
    
    context = {
        "categories":categories
    }
    return render(request, 'core/category-list.html', context)

def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status="published", category=category)
    
    context = {
        "category":category,
        "products":products,
    }
    return render(request, "core/category-product-list.html", context)

def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors": vendors,
    }
    return render(request, "core/vendor-list.html", context)

def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(vendor=vendor, product_status="published")
    context = {
        "vendor": vendor,
        "products": products,
    }
    return render(request, "core/vendor-detail-list.html", context)

def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)
    p_image = product.p_images.all()
    
    reviews = ProductReview.objects.filter(product=product).order_by("-date")
    
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    
    review_form = ProductReviewForm()
    # p_image = product.p_images.all()
    
    make_review =  True
    
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
        
        if user_review_count > 0:
            make_review = False
    
    context ={
        "p": product,
        "p_image": p_image,
        "review_form": review_form,
        "make_review": make_review,
        "reviews": reviews,
        "average_rating": average_rating,
        "products": products,
        
        
    }
    
    return render(request, "core/product-detail.html", context)

def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")
    
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])
        
    context = {
        "products": products,
        "tag": tag,
    }
    return render(request, "core/tag.html", context)

def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user
    
    review = ProductReview.objects.create(
        user=user, 
        product=product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )
    
    context = {
        'user': user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],

    }
    
    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))
    
    return JsonResponse(
      {  
        'bool': True,
        'context': context,
        'average_reviews': average_reviews, 
      }
    )
    
def search_view(request): 
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products": products,
        "query": query,
    }
    return render(request, "core/search.html", context)

def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")


    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status="published").order_by("-id").distinct()

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)


    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct() 

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct() 
    
    
    data = render_to_string("core/async/product-list.html", {"products": products})
    return JsonResponse({"data": data})

def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'image': request.GET['image'],
        'price': request.GET['price'],
        'pid': request.GET['pid'],
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:

            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data

    else:
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({"data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})


def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session["cart_data_obj"].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
        return render(request, "core/cart.html",{"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    else:
        messages.warning(request, "Your cart is emty")
        return redirect("core:index")

def delete_item_from_cart(request):
    cart_total_amount = 0
    product_id = str(request.GET["id"])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session["cart_data_obj"].items():
            cart_total_amount += int(item['qty']) * float(item['price'])    
        
    context = render_to_string("core/async/cart-list.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    
    return JsonResponse({"data": context, 'totalcartitems': len(request.session['cart_data_obj'])})

def update_cart(request):
    cart_total_amount = 0
    product_id = str(request.GET["id"])
    product_qty = request.GET["qty"]
    
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = product_qty
            request.session['cart_data_obj'] = cart_data
            
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session["cart_data_obj"].items():
            cart_total_amount += int(item['qty']) * float(item['price'])    
        
    context = render_to_string("core/async/cart-list.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    
    return JsonResponse({"data": context, 'totalcartitems': len(request.session['cart_data_obj'])})

@login_required
def checkout_view(request):
    cart_total_amount = 0
    total_amount = 0
    
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session["cart_data_obj"].items():
            total_amount += int(item['qty']) * float(item['price'])   
        order = CartOrder.objects.create(
            user=request.user,
            price=total_amount,
        )
        for p_id, item in request.session["cart_data_obj"].items():
            cart_total_amount += int(item['qty']) * float(item['price']) 
            cart_order_products = CartOrderItems.objects.create(
                order=order,
                invoice_no ="INVOICE_NO" + str(order.id),
                item=item['title'],
                image=item['image'],
                qty=item['qty'],
                price=item['price'],
                total=float(item['qty']) * float(item['price'])
            )
    
    host = request.get_host()
    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': cart_total_amount,
        'item_name': item,
        'invoice': 'INV-'+str(order.id),
        'currency_code': 'USD',

templates/core/async/product-list.html
{% for p in products %}
<div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
    <div class="product-cart-wrap mb-30">
        <div class="product-img-action-wrap">
            <div class="product-img product-img-zoom">
                <a href="{% url 'core:product-detail' p.pid %}">
                    <img class="default-img" src="{{ p.image.url }}" alt="" style="height: 280px; width: 280px; object-fit: cover;"   />
                    <img class="hover-img" src="{{ p.image.url }}" alt=""  style="height: 280px; width: 280px; object-fit: cover;"  />

                </a>
            </div>
            <div class="product-action-1">
                <a aria-label="Add To Wishlist"  class="action-btn add-to-wishlist" data-product-item="{{p.id}}"><i class="fi-rs-heart"></i></a>
                <!-- <a aria-label="Compare" class="action-btn" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a> -->
                <a href="{% url 'core:product-detail' p.pid %}" class="action-btn"><i class="fi-rs-eye"></i></a>
            </div>
            <div class="product-badges product-badges-position product-badges-mrg">
                <span class="hot">-{{p.get_precentage|floatformat:0}}%</span>
            </div>
        </div>
        <div class="product-content-wrap">
            <div class="product-category">
                <a href="shop-grid-right.html">{{ p.category.title }}</a>
            </div>
            <h2><a href="{% url 'core:product-detail' p.pid %}">{{ p.title }}</a></h2>
            <div class="product-rate-cover">
                <!-- <div class="product-rate d-inline-block"> -->
                    <!-- <div class="product-rating" style="width: 20%"></div> -->
                <!-- </div> -->
                <i class="fas fa-star text-warning"></i>
                <span class="font-small ml-5 text-muted"> ({{ p.reviews.all.count }})</span>
            </div>
            <div>
                <span class="font-small text-muted">By <a href="{% url 'core:vendor-detail' p.vendor.vid %}">{{p.vendor.title}}</a></span>
            </div>
            <div class="product-card-bottom">
                <div class="product-price">
                    <span>$</span> <span class="current-product-price-{{ p.id }}">{{p.price}}</span>
                    <span class="old-price">${{p.old_price}}</span>
                </div>
                <div class="add-cart">
                    <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ p.id }}">
                    <input type="hidden" class="product-pid-{{ p.id }}" value="{{ p.pid }}">
                    <input type="hidden" class="product-image-{{ p.id }}" value="{{ p.image.url }}">
                    <input type="hidden" class="product-id-{{ p.id }}" value="{{ p.id }}">
                    <input type="hidden" class="product-title-{{ p.id }}" value="{{ p.title }}">

                    <div class="d-flex">
                        <button class="add add-to-cart-btn" data-index="{{ p.id }}" style="border: none;" id="add-to-cart-btn"><i class="fi-rs-shopping-cart mr-5"></i>Add</button>
                        <button style="border: none; background: none;" class="add-to-wishlist" data-product-item="{{p.id}}"><i class="fi-rs-heart" style="fill: aqua;"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

templates/core/async/wishlist-list.html
    <main class="main" id="wishlist-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop <span></span> Fillter
                </div>
            </div>
        </div>
        <div class="container mb-30 mt-50">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <div class="mb-50">
                        <h1 class="heading-2 mb-10">Your Wishlist</h1>
                        <h6 class="text-body">There are <span class="text-brand">5</span> products in this list</h6>
                    </div>
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="" />
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col" colspan="2">Product</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Stock Status</th>
                                    <th scope="col">Action</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for w in wishlist%}
                                <tr>
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox2" value="" />
                                        <label class="form-check-label" for="exampleCheckbox2"></label>
                                    </td>
                                    <td class="image product-thumbnail"><img src="{{w.product.image.url}}" alt="#" /></td>
                                    <td class="product-des product-name">
                                        <h6><a class="product-name mb-10" href="{%url 'core:product-detail' w.product.pid%}">{{w.product.title|truncatechars:30}}</a></h6>
                                        
                                    </td>
                                    <td class="price" data-title="Price">
                                        
                                        <h3 class="current-price text-brand" style="display: inline;">$</h3><h3 class="current-price text-brand current-price current-product-price-{{w.product.id}}" style="display: inline;" id="current-product-price">{{w.product.price|floatformat:2}}</h3>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <span class="stock-status in-stock mb-0"> {%if w.product.in_stock %} In Stock {%else%} Out of stock {%endif%}</span>
                                    </td>
                                    <td class="text-right" data-title="Cart">
                                        <input type="hidden" id="product-quantity" value="1" class="product-quantity-{{w.product.id}}">
                                        <input type="hidden" class="product-pid-{{w.product.id}}" value={{w.product.pid}}>
                                        <input type="hidden" class="product-image-{{w.product.id}}" value={{w.product.image.url}}>
                                        <input type="hidden" class="product-id-{{w.product.id}}" value={{w.product.id}}>
                                        <input type="hidden" class="product-title-{{w.product.id}}" value={{w.product.title}}>
                                                        
                                        <button class="btn btn-sm add-to-cart-btn" data-index={{w.product.id}}>Add to cart</button>
                                    </td>
                                    <td class="action text-center" data-title="Remove">
                                        <button style="border: none; background: none;" data-wishlist-product="{{w.id}}" class="text-body delete-wishlist-product"><i class="fi-rs-trash"></i></button>
                                    </td>
                                </tr>
                               
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>